site_name: ConfigModel_MCMC
nav:
    - Home: index.md
    - Examples: example.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
deploy:
    skip_cleanup: true